public class oopsConcept {

    // * A real world entity which has states and behaviour is called object
    //  States == variables(Properties)
    //  Behaviour == Methods(Actions)
    
    // * Blueprint of an object is called class
    //  In a class we can create 1 or more objects
    
    //
    // * Inheritence = Inherite the properties of parent class
    //  A class can be created by extending the existing class
    //  Promoting the code reusebility 
    //  Establishment of class hierarchy
    //  For extendes the properties the class must have virtual or abstract 
    //  Any method of parent class denoted as virtual can be override in the child class
    
    // * Abstraction = Showing the functionality and hiding the implementation(internal details)
    
    // * Polymorphism = When the same task done differently is know as polymorphism 
    
    // * Incapsulation = Wrapping the code and the data in a unit 
    //  Class is example of Incapsulation
    
    //  * This keyword can not be use for static variable and static method 
    // * This keyword can be use for instance variable and instance method 
    
}